version: '3.8'
services:
  api: 
    build: .
    environment:
      - HTTP_PORT=3000
      - POOL_SIZE=30
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 1G
    network_mode: "host"
  postgres:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=lucas
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G
    network_mode: "host"
volumes:
  postgres:
